// <auto-generated />
using CCSOFTWARESOLUTIONS.Assets.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CCSOFTWARESOLUTIONS.Assets.Data.Migrations
{
    [DbContext(typeof(AssetsContext))]
    [Migration("20200501053328_CreateAssetsTracking")]
    partial class CreateAssetsTracking
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CCSOFTWARESOLUTIONS.Assets.Domain.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AssetTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssetTypeId");

                    b.ToTable("Asset");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssetTypeId = 1,
                            Description = "Inspiron",
                            Manufacturer = "Dell",
                            Model = "CO61-410US",
                            SerialNumber = "NXP-157-I",
                            TagNumber = "1A1"
                        },
                        new
                        {
                            Id = 2,
                            AssetTypeId = 1,
                            Description = "Hnspiron",
                            Manufacturer = "HP",
                            Model = "BO61-410US",
                            SerialNumber = "HXP-157-I",
                            TagNumber = "2A1"
                        },
                        new
                        {
                            Id = 3,
                            AssetTypeId = 1,
                            Description = "Anspiron",
                            Manufacturer = "Acer",
                            Model = "AO61-410US",
                            SerialNumber = "AXP-157-I",
                            TagNumber = "3A1"
                        },
                        new
                        {
                            Id = 4,
                            AssetTypeId = 2,
                            Description = "AMnspiron",
                            Manufacturer = "Acer",
                            Model = "AMO61-410US",
                            SerialNumber = "AMXP-157-I",
                            TagNumber = "4MA1"
                        },
                        new
                        {
                            Id = 5,
                            AssetTypeId = 2,
                            Description = "LMnspiron",
                            Manufacturer = "LG",
                            Model = "LMO61-410US",
                            SerialNumber = "LMXP-157-I",
                            TagNumber = "3MA1"
                        },
                        new
                        {
                            Id = 6,
                            AssetTypeId = 2,
                            Description = "HMnspiron",
                            Manufacturer = "HP",
                            Model = "HMO61-410US",
                            SerialNumber = "HMXP-157-I",
                            TagNumber = "3HA1"
                        },
                        new
                        {
                            Id = 7,
                            AssetTypeId = 3,
                            Description = "APnspiron",
                            Manufacturer = "Avaya",
                            Model = "APO61-410US",
                            SerialNumber = "APXP-157-I",
                            TagNumber = "3PA1"
                        },
                        new
                        {
                            Id = 8,
                            AssetTypeId = 3,
                            Description = "CPnspiron",
                            Manufacturer = "Cisco",
                            Model = "CPO61-410US",
                            SerialNumber = "CPXP-157-I",
                            TagNumber = "3CA1"
                        },
                        new
                        {
                            Id = 9,
                            AssetTypeId = 3,
                            Description = "PPnspiron",
                            Manufacturer = "Polycom",
                            Model = "PPO61-410US",
                            SerialNumber = "PPXP-157-I",
                            TagNumber = "3PPA1"
                        });
                });

            modelBuilder.Entity("CCSOFTWARESOLUTIONS.Assets.Domain.AssetType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AssetType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Computer"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Monitor"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Phone"
                        });
                });

            modelBuilder.Entity("CCSOFTWARESOLUTIONS.Assets.Domain.Asset", b =>
                {
                    b.HasOne("CCSOFTWARESOLUTIONS.Assets.Domain.AssetType", "AssetType")
                        .WithMany("Asset")
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
